version: "3.9"

services:
    # https://hub.docker.com/_/mariadb
    mariadb:
        image: mariadb:latest
        restart: always
        environment:
            - MARIADB_ROOT_PASSWORD=mariadb
        volumes:
            - db_data:/var/lib/mysql

    appcron:
        build: 
            context: ./image-cron-php
            # dockerfile: Dockerfile
            # target: cron-php
            # target: cron-php-chromium
            target: cron-php-chromium-jupyter
        restart: always
        # extra_hosts:
            # FIXME: not working 
            # - "gateway.docker.internal:host-gateway"
            # - "host.docker.internal:host-gateway"
        ports:
            # - 9000:9000
            - 3666:80
            # - 25:25 # smtp # problem: port already in use
        environment:
            # FIXME: automatic setup of these variables from docker ?!
            - CONTAINER_NAME=appcron
            # - CONTAINER_PORT=80
            - APP_PHP=../php/index.php
            # - PHP_ROOT=/app/php
            # - PHP_SERVER=php -S appcron:4321 -t /app/php/public /app/php/public/index.php
            # - PHP_SERVER=php -S appcron:4321 -t /app/root /app/root/index.php
            # - PHP_SERVER=php-fpm82 -R -F 
            # warning: dev only
            - ADMINER_PASSWORD=admin
        # warning: if overriding files in images, permissions may be wrong (+x)
        volumes:
            - ./minute:/app/minute
            - ./docker-setup/php-fpm-www.conf:/etc/php82/php-fpm.d/www.conf
            - ./php:/app/php
            - ./my-data:/app/my-data
            - app_tmp:/app/tmp

    # https://hub.docker.com/_/nginx
    nginx-webserver:
        image: nginx:latest
        restart: always
        ports:
            - "${XP_ENV_PORT:-4321}:80"
        depends_on:
            - appcron
        volumes:
            - ./docker-setup/nginx-templates:/etc/nginx/templates

    # playwright-node:
    #     build: 
    #         context: ./image-playwright
    #         dockerfile: Dockerfile
    #         target: node-playwright
    #     restart: always
    #     environment:
    #         # for X11
    #         - DISPLAY=host.docker.internal:0

    php-fpm-jupyter:
        build:
            context: ./image-php-fpm-jupyter
            dockerfile: Dockerfile
            target: php-fpm-jupyter
        restart: always
        environment:
            # for X11
            - DISPLAY=host.docker.internal:0
        volumes:
            - ./php-jupyter:/var/www/html
            - ./image-php-fpm-jupyter/docker/entrypoint.sh:/usr/local/bin/docker-php-entrypoint
            - ./image-php-fpm-jupyter/cron:/var/app_cron
            - ./image-php-fpm-jupyter/cron/app_cron:/etc/cron.d/app_cron

volumes:
    db_data:
    app_tmp:

#location / {
#        root   /usr/share/nginx/html;
#        index  index.html index.htm;
#    }

# /etc/php82/php-fpm.d/www.conf